// AUTO-GENERATED by web/scripts/derive-facts.mjs at prebuild.
// DO NOT EDIT — re-run `npm run prebuild` (or just `npm run build`) after changing the parent repo.
// Runtime KV snapshots must use this shape and include exact source provenance.

export interface ProviderFact { id: string; label: string; env: string }

export interface ModelFact {
  id: string;
  provider: string | null;
  contextWindow: number | null;
  maxOutput: number | null;
  reasoning: boolean;
  addedAt: string | null;
}

export interface PublishedReleaseFact {
  tag: string;
  version: string;
  publishedAt: string;
  url: string;
}

export interface RepoFacts {
  generatedAt: string;
  sourceRevision: string | null;
  sourceCommittedAt: string | null;
  version: string | null;
  crates: string[];
  sandboxBackends: string[];
  providers: ProviderFact[];
  models: ModelFact[];
  defaultModel: string | null;
  nodeEngines: string | null;
  toolCount: number | null;
  license: string | null;
  latestPublishedRelease: PublishedReleaseFact | null;
}

export const FACTS: RepoFacts = {
  "generatedAt": "2026-10-02T18:06:32.682Z",
  "sourceRevision": null,
  "sourceCommittedAt": null,
  "version": "0.10.1",
  "crates": [
    "agent",
    "app-server",
    "build-support",
    "cli",
    "cloud-facts",
    "command-contract",
    "config",
    "core",
    "execpolicy",
    "hooks",
    "lane",
    "localization",
    "mcp",
    "memory",
    "models",
    "palette",
    "paths",
    "protocol",
    "release",
    "runtime",
    "sanitize",
    "secrets",
    "state",
    "telemetry",
    "tools",
    "tui",
    "workflow",
    "workflow-js"
  ],
  "sandboxBackends": [
    "seatbelt (macOS, when available)",
    "bubblewrap (Linux, opt-in when installed)"
  ],
  "providers": [
    {
      "id": "deepseek",
      "label": "DeepSeek",
      "env": "DEEPSEEK_API_KEY"
    },
    {
      "id": "deepseek-anthropic",
      "label": "DeepSeek Anthropic",
      "env": "DEEPSEEK_API_KEY / ANTHROPIC_API_KEY"
    },
    {
      "id": "nvidia-nim",
      "label": "NVIDIA NIM",
      "env": "NVIDIA_API_KEY / NVIDIA_NIM_API_KEY"
    },
    {
      "id": "openai",
      "label": "OpenAI-compatible",
      "env": "OPENAI_API_KEY"
    },
    {
      "id": "atlascloud",
      "label": "AtlasCloud",
      "env": "ATLASCLOUD_API_KEY"
    },
    {
      "id": "wanjie-ark",
      "label": "Wanjie Ark",
      "env": "WANJIE_ARK_API_KEY / WANJIE_API_KEY / WANJIE_MAAS_API_KEY"
    },
    {
      "id": "volcengine",
      "label": "Volcengine Ark",
      "env": "VOLCENGINE_API_KEY / VOLCENGINE_ARK_API_KEY / ARK_API_KEY"
    },
    {
      "id": "openrouter",
      "label": "OpenRouter",
      "env": "OPENROUTER_API_KEY"
    },
    {
      "id": "orcarouter",
      "label": "OrcaRouter",
      "env": "ORCAROUTER_API_KEY"
    },
    {
      "id": "xiaomi-mimo",
      "label": "Xiaomi MiMo",
      "env": "XIAOMI_MIMO_TOKEN_PLAN_API_KEY / MIMO_TOKEN_PLAN_API_KEY / XIAOMI_MIMO_API_KEY / XIAOMI_API_KEY / MIMO_API_KEY"
    },
    {
      "id": "novita",
      "label": "Novita AI",
      "env": "NOVITA_API_KEY"
    },
    {
      "id": "fireworks",
      "label": "Fireworks AI",
      "env": "FIREWORKS_API_KEY"
    },
    {
      "id": "siliconflow",
      "label": "SiliconFlow",
      "env": "SILICONFLOW_API_KEY"
    },
    {
      "id": "siliconflow-CN",
      "label": "SiliconFlow CN",
      "env": "SILICONFLOW_API_KEY"
    },
    {
      "id": "arcee",
      "label": "Arcee AI",
      "env": "ARCEE_API_KEY"
    },
    {
      "id": "moonshot",
      "label": "Moonshot/Kimi",
      "env": "MOONSHOT_API_KEY / KIMI_API_KEY"
    },
    {
      "id": "sglang",
      "label": "SGLang",
      "env": "SGLANG_API_KEY"
    },
    {
      "id": "vllm",
      "label": "vLLM",
      "env": "VLLM_API_KEY"
    },
    {
      "id": "ollama",
      "label": "Ollama",
      "env": "OLLAMA_API_KEY"
    },
    {
      "id": "ollama-cloud",
      "label": "Ollama Cloud",
      "env": "OLLAMA_CLOUD_API_KEY / OLLAMA_API_KEY"
    },
    {
      "id": "huggingface",
      "label": "Hugging Face",
      "env": "HUGGINGFACE_API_KEY / HF_TOKEN"
    },
    {
      "id": "together",
      "label": "Together AI",
      "env": "TOGETHER_API_KEY"
    },
    {
      "id": "qianfan",
      "label": "Baidu Qianfan",
      "env": "QIANFAN_API_KEY / BAIDU_QIANFAN_API_KEY"
    },
    {
      "id": "openai-codex",
      "label": "OpenAI Codex",
      "env": "ChatGPT OAuth via `codewhale auth chatgpt`; optional consented Codex CLI credentials (OPENAI_CODEX_ACCESS_TOKEN / CODEX_ACCESS_TOKEN override)"
    },
    {
      "id": "anthropic",
      "label": "Anthropic",
      "env": "ANTHROPIC_API_KEY"
    },
    {
      "id": "openmodel",
      "label": "OpenModel",
      "env": "OPENMODEL_API_KEY"
    },
    {
      "id": "zai",
      "label": "Z.ai",
      "env": "ZAI_API_KEY / Z_AI_API_KEY"
    },
    {
      "id": "stepfun",
      "label": "StepFun",
      "env": "STEPFUN_API_KEY / STEP_API_KEY"
    },
    {
      "id": "minimax",
      "label": "MiniMax",
      "env": "MINIMAX_API_KEY"
    },
    {
      "id": "minimax-anthropic",
      "label": "MiniMax (Anthropic-compatible)",
      "env": "MINIMAX_API_KEY"
    },
    {
      "id": "deepinfra",
      "label": "DeepInfra",
      "env": "DEEPINFRA_API_KEY / DEEPINFRA_TOKEN"
    },
    {
      "id": "sakana",
      "label": "Sakana AI",
      "env": "FUGU_API_KEY / SAKANA_API_KEY"
    },
    {
      "id": "longcat",
      "label": "Meituan LongCat",
      "env": "LONGCAT_API_KEY"
    },
    {
      "id": "opencode-go",
      "label": "OpenCode Go",
      "env": "OPENCODE_GO_API_KEY"
    },
    {
      "id": "opencode-zen",
      "label": "OpenCode Zen",
      "env": "OPENCODE_ZEN_API_KEY / OPENCODE_API_KEY"
    },
    {
      "id": "meta",
      "label": "Meta Model API",
      "env": "META_MODEL_API_KEY / MODEL_API_KEY"
    },
    {
      "id": "xai",
      "label": "xAI",
      "env": "XAI_API_KEY"
    },
    {
      "id": "mistral",
      "label": "Mistral AI",
      "env": "MISTRAL_API_KEY"
    },
    {
      "id": "google",
      "label": "Google Gemini",
      "env": "GOOGLE_API_KEY / GEMINI_API_KEY"
    },
    {
      "id": "modelscope",
      "label": "ModelScope",
      "env": "MODELSCOPE_API_KEY"
    },
    {
      "id": "telecomjs",
      "label": "TelecomJS TokenHub",
      "env": "TELECOMJS_API_KEY"
    },
    {
      "id": "edenai",
      "label": "Eden AI",
      "env": "EDENAI_API_KEY"
    },
    {
      "id": "zenmux",
      "label": "ZenMux",
      "env": "ZENMUX_API_KEY"
    },
    {
      "id": "csdn",
      "label": "CSDN 星图 (Starmap)",
      "env": "CSDN_API_KEY"
    },
    {
      "id": "concentrate",
      "label": "Concentrate",
      "env": "CONCENTRATE_API_KEY"
    },
    {
      "id": "codewhale",
      "label": "Codewhale",
      "env": "CODEWHALE_API_KEY"
    },
    {
      "id": "modelstudio-token-plan",
      "label": "Model Studio Token Plan",
      "env": "MODELSTUDIO_API_KEY"
    },
    {
      "id": "modelstudio-token-plan-anthropic",
      "label": "Model Studio Token Plan (Anthropic-compatible)",
      "env": "MODELSTUDIO_API_KEY"
    },
    {
      "id": "modelstudio-coding-plan",
      "label": "Model Studio Coding Plan",
      "env": "MODELSTUDIO_API_KEY"
    },
    {
      "id": "modelstudio-coding-plan-anthropic",
      "label": "Model Studio Coding Plan (Anthropic-compatible)",
      "env": "MODELSTUDIO_API_KEY"
    }
  ],
  "models": [
    {
      "id": "grok-4.7",
      "provider": "xAI",
      "contextWindow": 500000,
      "maxOutput": null,
      "reasoning": true,
      "addedAt": "2026-09-23"
    },
    {
      "id": "step-3.5-flash",
      "provider": "StepFun",
      "contextWindow": 256000,
      "maxOutput": null,
      "reasoning": true,
      "addedAt": "2026-09-19"
    },
    {
      "id": "step-3.5-flash-2603",
      "provider": "StepFun",
      "contextWindow": 256000,
      "maxOutput": null,
      "reasoning": true,
      "addedAt": "2026-09-19"
    },
    {
      "id": "step-5-preview",
      "provider": "StepFun",
      "contextWindow": 1000000,
      "maxOutput": 1000000,
      "reasoning": true,
      "addedAt": "2026-09-19"
    },
    {
      "id": "qwen3.5-flash",
      "provider": "Qwen",
      "contextWindow": null,
      "maxOutput": null,
      "reasoning": true,
      "addedAt": "2026-09-09"
    },
    {
      "id": "glm-5.3-flash",
      "provider": "Z.ai",
      "contextWindow": 1000000,
      "maxOutput": 131072,
      "reasoning": true,
      "addedAt": "2026-08-27"
    },
    {
      "id": "qwen3.8-flash",
      "provider": "Qwen",
      "contextWindow": 1000000,
      "maxOutput": 131072,
      "reasoning": true,
      "addedAt": "2026-08-27"
    },
    {
      "id": "deepseek-v4-flash-vision-exp",
      "provider": "DeepSeek",
      "contextWindow": 1000000,
      "maxOutput": 384000,
      "reasoning": true,
      "addedAt": "2026-08-21"
    },
    {
      "id": "claude-opus-5",
      "provider": "Anthropic",
      "contextWindow": 1000000,
      "maxOutput": 128000,
      "reasoning": true,
      "addedAt": "2026-08-17"
    },
    {
      "id": "gemini-3.7-flash",
      "provider": "Google",
      "contextWindow": 1048576,
      "maxOutput": 65536,
      "reasoning": false,
      "addedAt": "2026-08-17"
    },
    {
      "id": "kimi-k2.7-code-highspeed",
      "provider": "Moonshot/Kimi",
      "contextWindow": 262144,
      "maxOutput": 32768,
      "reasoning": true,
      "addedAt": "2026-08-17"
    },
    {
      "id": "gemini-2.5-flash",
      "provider": "Google",
      "contextWindow": 1048576,
      "maxOutput": 65536,
      "reasoning": false,
      "addedAt": "2026-08-14"
    },
    {
      "id": "gemini-2.5-pro",
      "provider": "Google",
      "contextWindow": 1048576,
      "maxOutput": 65536,
      "reasoning": false,
      "addedAt": "2026-08-14"
    },
    {
      "id": "gemini-3-pro-preview",
      "provider": "Google",
      "contextWindow": 1048576,
      "maxOutput": 65536,
      "reasoning": false,
      "addedAt": "2026-08-14"
    },
    {
      "id": "gemini-3.1-pro-preview",
      "provider": "Google",
      "contextWindow": 1048576,
      "maxOutput": 65536,
      "reasoning": false,
      "addedAt": "2026-08-14"
    },
    {
      "id": "gemini-3.5-flash",
      "provider": "Google",
      "contextWindow": 1048576,
      "maxOutput": 65536,
      "reasoning": false,
      "addedAt": "2026-08-14"
    },
    {
      "id": "gemini-3.5-flash-lite",
      "provider": "Google",
      "contextWindow": 1048576,
      "maxOutput": 65536,
      "reasoning": false,
      "addedAt": "2026-08-14"
    },
    {
      "id": "gemini-3.6-flash",
      "provider": "Google",
      "contextWindow": 1048576,
      "maxOutput": 65536,
      "reasoning": false,
      "addedAt": "2026-08-14"
    },
    {
      "id": "grok-4.6",
      "provider": "xAI",
      "contextWindow": 500000,
      "maxOutput": null,
      "reasoning": true,
      "addedAt": "2026-08-12"
    },
    {
      "id": "mistral-code-latest",
      "provider": "Mistral",
      "contextWindow": 256000,
      "maxOutput": null,
      "reasoning": false,
      "addedAt": "2026-08-09"
    },
    {
      "id": "mistral-large-latest",
      "provider": "Mistral",
      "contextWindow": 262144,
      "maxOutput": null,
      "reasoning": false,
      "addedAt": "2026-08-09"
    },
    {
      "id": "mistral-medium-latest",
      "provider": "Mistral",
      "contextWindow": 262144,
      "maxOutput": null,
      "reasoning": true,
      "addedAt": "2026-08-08"
    },
    {
      "id": "mistral-small-latest",
      "provider": "Mistral",
      "contextWindow": 262144,
      "maxOutput": null,
      "reasoning": true,
      "addedAt": "2026-08-08"
    },
    {
      "id": "muse-spark-1.2-contributor",
      "provider": "Meta",
      "contextWindow": 1000000,
      "maxOutput": 32000,
      "reasoning": true,
      "addedAt": "2026-08-06"
    },
    {
      "id": "muse-spark-1.2",
      "provider": "Meta",
      "contextWindow": 1000000,
      "maxOutput": 32000,
      "reasoning": true,
      "addedAt": "2026-08-05"
    },
    {
      "id": "glm-5.3",
      "provider": "Z.ai",
      "contextWindow": 1000000,
      "maxOutput": 131072,
      "reasoning": true,
      "addedAt": "2026-08-03"
    },
    {
      "id": "deepseek-flash",
      "provider": "DeepSeek",
      "contextWindow": 1000000,
      "maxOutput": 384000,
      "reasoning": true,
      "addedAt": "2026-08-02"
    },
    {
      "id": "qwen3.8-max",
      "provider": "Qwen",
      "contextWindow": 1000000,
      "maxOutput": 131072,
      "reasoning": true,
      "addedAt": "2026-08-02"
    },
    {
      "id": "qwen3.8-max-preview",
      "provider": "Qwen",
      "contextWindow": 1000000,
      "maxOutput": 131072,
      "reasoning": true,
      "addedAt": "2026-08-02"
    },
    {
      "id": "kimi-for-coding-highspeed",
      "provider": "Moonshot/Kimi",
      "contextWindow": 262144,
      "maxOutput": null,
      "reasoning": true,
      "addedAt": "2026-07-27"
    },
    {
      "id": "qwen3.5-plus",
      "provider": "Qwen",
      "contextWindow": null,
      "maxOutput": null,
      "reasoning": true,
      "addedAt": "2026-07-26"
    },
    {
      "id": "kimi-k3",
      "provider": "Moonshot/Kimi",
      "contextWindow": 1048576,
      "maxOutput": 131072,
      "reasoning": true,
      "addedAt": "2026-07-17"
    },
    {
      "id": "thinkingmachines/inkling",
      "provider": "Together",
      "contextWindow": null,
      "maxOutput": null,
      "reasoning": true,
      "addedAt": "2026-07-15"
    },
    {
      "id": "claude-fable-5",
      "provider": "Anthropic",
      "contextWindow": 1000000,
      "maxOutput": 128000,
      "reasoning": true,
      "addedAt": "2026-07-09"
    },
    {
      "id": "claude-sonnet-5",
      "provider": "Anthropic",
      "contextWindow": 1000000,
      "maxOutput": 128000,
      "reasoning": true,
      "addedAt": "2026-07-09"
    },
    {
      "id": "gpt-5.6",
      "provider": "OpenAI",
      "contextWindow": 1050000,
      "maxOutput": 128000,
      "reasoning": true,
      "addedAt": "2026-07-09"
    },
    {
      "id": "gpt-5.6-luna",
      "provider": "OpenAI",
      "contextWindow": 1050000,
      "maxOutput": 128000,
      "reasoning": true,
      "addedAt": "2026-07-09"
    },
    {
      "id": "gpt-5.6-sol",
      "provider": "OpenAI",
      "contextWindow": 1050000,
      "maxOutput": 128000,
      "reasoning": true,
      "addedAt": "2026-07-09"
    },
    {
      "id": "gpt-5.6-terra",
      "provider": "OpenAI",
      "contextWindow": 1050000,
      "maxOutput": 128000,
      "reasoning": true,
      "addedAt": "2026-07-09"
    },
    {
      "id": "muse-spark-1.1",
      "provider": "Meta",
      "contextWindow": 1000000,
      "maxOutput": 32000,
      "reasoning": true,
      "addedAt": "2026-07-09"
    },
    {
      "id": "qwen3.7-plus",
      "provider": "Qwen",
      "contextWindow": 1000000,
      "maxOutput": 65536,
      "reasoning": true,
      "addedAt": "2026-07-09"
    },
    {
      "id": "grok-4.20-0309-non-reasoning",
      "provider": "xAI",
      "contextWindow": 2000000,
      "maxOutput": null,
      "reasoning": false,
      "addedAt": "2026-07-08"
    },
    {
      "id": "grok-4.20-0309-reasoning",
      "provider": "xAI",
      "contextWindow": 2000000,
      "maxOutput": null,
      "reasoning": true,
      "addedAt": "2026-07-08"
    },
    {
      "id": "grok-4.3",
      "provider": "xAI",
      "contextWindow": 1000000,
      "maxOutput": null,
      "reasoning": true,
      "addedAt": "2026-07-08"
    },
    {
      "id": "grok-4.5",
      "provider": "xAI",
      "contextWindow": 500000,
      "maxOutput": null,
      "reasoning": true,
      "addedAt": "2026-07-08"
    },
    {
      "id": "grok-build",
      "provider": "xAI",
      "contextWindow": 512000,
      "maxOutput": null,
      "reasoning": true,
      "addedAt": "2026-07-08"
    },
    {
      "id": "grok-composer-2.5-fast",
      "provider": "xAI",
      "contextWindow": 200000,
      "maxOutput": null,
      "reasoning": false,
      "addedAt": "2026-07-08"
    },
    {
      "id": "fugu-ultra",
      "provider": null,
      "contextWindow": 1000000,
      "maxOutput": 131000,
      "reasoning": true,
      "addedAt": "2026-07-06"
    },
    {
      "id": "fugu-ultra-20260615",
      "provider": null,
      "contextWindow": 1000000,
      "maxOutput": 131000,
      "reasoning": true,
      "addedAt": "2026-06-28"
    },
    {
      "id": "mimo-v2.5-pro-ultraspeed",
      "provider": "Xiaomi MiMo",
      "contextWindow": 1000000,
      "maxOutput": 131072,
      "reasoning": true,
      "addedAt": "2026-06-22"
    },
    {
      "id": "kimi-k2.5",
      "provider": "Moonshot/Kimi",
      "contextWindow": null,
      "maxOutput": null,
      "reasoning": true,
      "addedAt": "2026-06-21"
    },
    {
      "id": "claude-haiku-4-5",
      "provider": "Anthropic",
      "contextWindow": 200000,
      "maxOutput": 64000,
      "reasoning": false,
      "addedAt": "2026-06-14"
    },
    {
      "id": "claude-opus-4-8",
      "provider": "Anthropic",
      "contextWindow": 1000000,
      "maxOutput": 128000,
      "reasoning": true,
      "addedAt": "2026-06-14"
    },
    {
      "id": "gpt-5-codex",
      "provider": "OpenAI Codex",
      "contextWindow": 400000,
      "maxOutput": 128000,
      "reasoning": true,
      "addedAt": "2026-06-14"
    },
    {
      "id": "gpt-5.3-codex",
      "provider": "OpenAI",
      "contextWindow": 400000,
      "maxOutput": 128000,
      "reasoning": true,
      "addedAt": "2026-06-14"
    },
    {
      "id": "gpt-5.5-pro",
      "provider": "OpenAI",
      "contextWindow": 1050000,
      "maxOutput": 128000,
      "reasoning": true,
      "addedAt": "2026-06-14"
    },
    {
      "id": "glm-5.2",
      "provider": "Z.ai",
      "contextWindow": 1000000,
      "maxOutput": 131072,
      "reasoning": true,
      "addedAt": "2026-06-12"
    },
    {
      "id": "kimi-k2.7-code",
      "provider": "Moonshot/Kimi",
      "contextWindow": 262144,
      "maxOutput": 32768,
      "reasoning": true,
      "addedAt": "2026-06-12"
    },
    {
      "id": "minimax-m2.7",
      "provider": "MiniMax",
      "contextWindow": 204800,
      "maxOutput": 131072,
      "reasoning": true,
      "addedAt": "2026-06-12"
    },
    {
      "id": "minimax-m3",
      "provider": "MiniMax",
      "contextWindow": 1000000,
      "maxOutput": 524288,
      "reasoning": true,
      "addedAt": "2026-06-12"
    },
    {
      "id": "step-3.7-flash",
      "provider": "StepFun",
      "contextWindow": 256000,
      "maxOutput": 256000,
      "reasoning": true,
      "addedAt": "2026-06-12"
    },
    {
      "id": "claude-sonnet-4-6",
      "provider": "Anthropic",
      "contextWindow": 1000000,
      "maxOutput": 128000,
      "reasoning": true,
      "addedAt": "2026-06-11"
    },
    {
      "id": "gpt-5.5",
      "provider": "OpenAI",
      "contextWindow": 1050000,
      "maxOutput": 128000,
      "reasoning": true,
      "addedAt": "2026-06-08"
    },
    {
      "id": "qwen3.6-flash",
      "provider": "Qwen",
      "contextWindow": 1000000,
      "maxOutput": 65536,
      "reasoning": true,
      "addedAt": "2026-06-02"
    },
    {
      "id": "qwen3.6-plus",
      "provider": "Qwen",
      "contextWindow": null,
      "maxOutput": null,
      "reasoning": true,
      "addedAt": "2026-06-02"
    },
    {
      "id": "trinity-mini",
      "provider": "Arcee",
      "contextWindow": 128000,
      "maxOutput": null,
      "reasoning": true,
      "addedAt": "2026-06-02"
    },
    {
      "id": "glm-5.1",
      "provider": "Z.ai",
      "contextWindow": 202752,
      "maxOutput": 131072,
      "reasoning": true,
      "addedAt": "2026-05-31"
    },
    {
      "id": "qwen3.6-35b-a3b",
      "provider": "Qwen",
      "contextWindow": null,
      "maxOutput": null,
      "reasoning": false,
      "addedAt": "2026-05-31"
    },
    {
      "id": "qwen3.7-max",
      "provider": "Qwen",
      "contextWindow": 1000000,
      "maxOutput": 65536,
      "reasoning": true,
      "addedAt": "2026-05-31"
    },
    {
      "id": "trinity-large-thinking",
      "provider": "Arcee",
      "contextWindow": 262144,
      "maxOutput": 262144,
      "reasoning": true,
      "addedAt": "2026-05-31"
    },
    {
      "id": "mimo-v2.5",
      "provider": "Xiaomi MiMo",
      "contextWindow": 1000000,
      "maxOutput": 131072,
      "reasoning": true,
      "addedAt": "2026-05-30"
    },
    {
      "id": "mimo-v2.5-pro",
      "provider": "Xiaomi MiMo",
      "contextWindow": 1000000,
      "maxOutput": 131072,
      "reasoning": true,
      "addedAt": "2026-05-30"
    },
    {
      "id": "kimi-for-coding",
      "provider": "Moonshot/Kimi",
      "contextWindow": 262144,
      "maxOutput": null,
      "reasoning": true,
      "addedAt": "2026-05-25"
    },
    {
      "id": "kimi-k2.6",
      "provider": "Moonshot/Kimi",
      "contextWindow": 262144,
      "maxOutput": 32768,
      "reasoning": true,
      "addedAt": "2026-05-25"
    },
    {
      "id": "deepseek-coder:1.3b",
      "provider": "DeepSeek",
      "contextWindow": null,
      "maxOutput": null,
      "reasoning": false,
      "addedAt": "2026-05-06"
    },
    {
      "id": "deepseek-v4-flash",
      "provider": "DeepSeek",
      "contextWindow": 1000000,
      "maxOutput": 384000,
      "reasoning": true,
      "addedAt": "2026-04-23"
    },
    {
      "id": "deepseek-v4-pro",
      "provider": "DeepSeek",
      "contextWindow": 1000000,
      "maxOutput": 384000,
      "reasoning": true,
      "addedAt": "2026-04-23"
    },
    {
      "id": "deepseek-reasoner",
      "provider": "DeepSeek",
      "contextWindow": null,
      "maxOutput": null,
      "reasoning": false,
      "addedAt": "2026-03-02"
    }
  ],
  "defaultModel": "deepseek-flash",
  "nodeEngines": ">=18",
  "toolCount": 80,
  "license": "MIT",
  "latestPublishedRelease": {
    "tag": "v0.10.0",
    "version": "0.10.0",
    "publishedAt": "2026-09-22T17:28:34Z",
    "url": "https://github.com/codewhale-hq/CodeWhale/releases/tag/v0.10.0"
  }
};
