// Build the single-file host bundle that the Rust binary embeds.
//
// `dist/` is committed so `cargo build` never needs Node or npm; CI rebuilds
// and fails on drift (`git diff --exit-code dist`).
import { build } from 'esbuild'
import { createHash } from 'node:crypto'
import { existsSync, readFileSync, readdirSync, rmSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const outdir = join(here, 'dist')
mkdirSync(outdir, { recursive: true })

// Built-in host modules (tier 0): each `src/builtin/<id>.ts` is built to
// `dist/builtin/<id>.mjs`, the file the core activates under the owner id
// `host:<id>`, and `dist/builtin-modules.json` records the SHA-256 of every
// one. The Rust table `BUILTIN_MODULES` (src/extension_host/tier.rs) pins the
// same digests, and a Rust test fails when the two disagree. The committed
// host:mcp module is an explicitly selected SDK adapter over Rust broker sessions.
// They are built before the host bundle, which embeds the digests.
const builtinSource = join(here, 'src/builtin')
const builtinOut = join(outdir, 'builtin')
rmSync(builtinOut, { recursive: true, force: true }) // a removed module leaves nothing behind
const builtinIds = existsSync(builtinSource)
  ? readdirSync(builtinSource)
      .filter((file) => file.endsWith('.ts'))
      .map((file) => file.slice(0, -'.ts'.length))
      .sort()
  : []
const builtinDigests = {}
const builtinMetafiles = []
for (const id of builtinIds) {
  // Mirrors `valid_module_id` in tier.rs: the id is also a file name.
  if (!/^[a-z][a-z0-9-]{0,63}$/.test(id)) throw new Error(`src/builtin/${id}.ts is not a valid built-in module name`)
  const outfile = join(builtinOut, `${id}.mjs`)
  const built = await build({
    entryPoints: [join(builtinSource, `${id}.ts`)],
    outfile,
    absWorkingDir: here,
    metafile: true,
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node22.19',
    sourcemap: false,
    minify: false,
    legalComments: 'none',
    charset: 'utf8',
    logLevel: 'warning',
    banner: { js: `// codewhale built-in host module ${id} — generated by crates/tui/extension-host/build.mjs; do not edit.` },
  })
  builtinMetafiles.push(built.metafile)
  builtinDigests[id] = createHash('sha256').update(readFileSync(outfile)).digest('hex')
}
writeFileSync(join(outdir, 'builtin-modules.json'), JSON.stringify({ modules: builtinDigests }, null, 2) + '\n')

const compositionAlias = {
  '@deepseek-ai/cordis-plugin-loader': join(here, 'src/dsh/upstream/loader/src/index.ts'),
}

const hostBuild = await build({
  alias: compositionAlias,
  entryPoints: [join(here, 'src/main.ts')],
  outfile: join(outdir, 'codewhale-extension-host.mjs'),
  absWorkingDir: here,
  metafile: true,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22.19',
  // Deterministic output: no sourcemap paths, no timestamps, no minification
  // (a readable bundle keeps the reviewed-bytes story honest).
  sourcemap: false,
  minify: false,
  legalComments: 'none',
  charset: 'utf8',
  logLevel: 'warning',
  // `host/hello` reports these, so the core can check the bundle and its own
  // pinned table agree (`tier.ts`, `builtinModuleDigests`).
  define: { __BUILTIN_MODULE_DIGESTS__: JSON.stringify(builtinDigests) },
  banner: {
    js: '// codewhale-extension-host — generated by crates/tui/extension-host/build.mjs; do not edit.\n// Third-party notices: LICENSES.txt next to this file.',
  },
})

// Test-only reviewed hook bridge: Node tests exercise the exact pinned parser.
await build({
  entryPoints: [join(here, 'src/dsh/shell-hooks.ts')],
  outfile: join(outdir, 'shell-hooks.mjs'),
  absWorkingDir: here,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22.19',
  sourcemap: false,
  minify: false,
  legalComments: 'none',
  charset: 'utf8',
  logLevel: 'warning',
})

// Trusted offline composition reviewer. Embedded beside the host, but has
// no HostRoot, RPC handler, plugin import or expression evaluation entrypoint.
const reviewBuild = await build({
  alias: compositionAlias,
  entryPoints: [join(here, 'src/dsh/review-main.ts')],
  outfile: join(outdir, 'dsh-composition-review.mjs'),
  absWorkingDir: here,
  metafile: true,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22.19',
  sourcemap: false,
  minify: false,
  legalComments: 'none',
  charset: 'utf8',
  logLevel: 'warning',
  banner: { js: '// trusted nonexecuting DSH composition reviewer; third-party notices: LICENSES.txt' },
})

// Test-only pure adapters: the production harness imports exactly this source.
await build({entryPoints:[join(here,'src/builtin/shared/stock-adapters.ts')],outfile:join(outdir,'stock-adapters.mjs'),bundle:true,platform:'node',format:'esm',target:'node22.19',sourcemap:false,minify:false,legalComments:'none',charset:'utf8',logLevel:'warning'})

// Test-only protocol module (codec + validators) so `node --test` can check
// the corpus against the exact code the host runs, without booting a host.
// Not embedded in the Rust binary.
await build({
  entryPoints: [join(here, 'src/protocol.ts')],
  outfile: join(outdir, 'protocol.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22.19',
  sourcemap: false,
  minify: false,
  legalComments: 'none',
  charset: 'utf8',
  logLevel: 'warning',
  banner: { js: '// generated by crates/tui/extension-host/build.mjs from src/protocol.ts; do not edit.' },
})

// Test-only RPC peer, for the unit tests of its cancellation. Not embedded.
await build({
  entryPoints: [join(here, 'src/rpc.ts')],
  outfile: join(outdir, 'rpc.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22.19',
  sourcemap: false,
  minify: false,
  legalComments: 'none',
  charset: 'utf8',
  logLevel: 'warning',
  banner: { js: '// generated by crates/tui/extension-host/build.mjs from src/rpc.ts; do not edit.' },
})

// Test-only skill-root shim, bundled so tests remain dependency-free before npm ci.
await build({
  entryPoints: [join(here, 'src/shims/skills.ts')],
  outfile: join(outdir, 'skills.mjs'),
  absWorkingDir: here,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22.19',
  sourcemap: false,
  minify: false,
  legalComments: 'none',
  charset: 'utf8',
  logLevel: 'warning',
  banner: { js: '// generated by crates/tui/extension-host/build.mjs from src/shims/skills.ts; do not edit.' },
})

// Source-focused raw roster tests use the same discovery/receipt adapter.
await build({entryPoints:[join(here,'src/dsh/agent-presets.ts')],outfile:join(outdir,'agent-presets.mjs'),alias:compositionAlias,bundle:true,platform:'node',format:'esm',target:'node22.19',sourcemap:false,minify:false,legalComments:'none',charset:'utf8',logLevel:'warning'})

// Third-party notices (`dist/LICENSES.txt`), generated from what the bundler
// actually put in the host bundle: every package that contributed an input
// file, with its own LICENSE file. A package added to or dropped from the
// bundle changes this file, and CI's `git diff --exit-code -- dist` then
// catches a stale one. The Rust core embeds this file and writes it beside the
// materialised bundle, so the banner's promise ("LICENSES.txt next to this
// file") holds for every installed copy.
const LICENSE_FILES = ['LICENSE', 'LICENSE.md', 'LICENSE.txt', 'LICENCE', 'LICENCE.md', 'license', 'license.md', 'COPYING']

function bundledPackages(metafile) {
  const found = new Map()
  for (const input of Object.keys(metafile.inputs)) {
    const marker = 'node_modules/'
    const at = input.lastIndexOf(marker)
    if (at < 0) continue
    const [first, second] = input.slice(at + marker.length).split('/')
    const name = first.startsWith('@') ? `${first}/${second}` : first
    found.set(name, join(here, input.slice(0, at + marker.length), name))
  }
  return [...found.entries()].sort(([a], [b]) => (a < b ? -1 : 1)).map(([name, root]) => ({ name, root }))
}

function readLicense(root, label) {
  for (const file of LICENSE_FILES) {
    try {
      return readFileSync(join(root, file), 'utf8').trim()
    } catch {}
  }
  throw new Error(`${label} is bundled but ships no LICENSE file in ${root}; add its notice by hand before releasing`)
}

// Source vendored into `src/` verbatim rather than imported from node_modules.
// The metafile cannot see these, so each names the file that carries the
// excerpt and the bundled package whose licence text it shares (checked below).
const EXCERPTED = [
  {
    name: '@deepseek-ai/dsh-tools',
    version: '0.1.7-alpha.2',
    license: 'MIT',
    file: 'src/dsh/dsh-tools-compat.js',
    licenseOf: '@deepseek-ai/dsh-util-values',
  },
]

const packageInputs = [hostBuild.metafile, reviewBuild.metafile, ...builtinMetafiles].flatMap(bundledPackages)
const packagesByIdentity = new Map()
for (const { name, root } of packageInputs) {
  const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
  if (typeof pkg.license !== 'string' || pkg.license.length === 0) throw new Error(`${name} declares no license in package.json`)
  const entry = { name: pkg.name, version: pkg.version, license: pkg.license, text: readLicense(root, name) }
  const identity = `${entry.name}@${entry.version}`
  const prior = packagesByIdentity.get(identity)
  if (prior && (prior.license !== entry.license || prior.text !== entry.text)) throw new Error(`${identity} contributes conflicting licence texts`)
  packagesByIdentity.set(identity, entry)
}
const packages = [...packagesByIdentity.values()]
if (packages.length === 0) throw new Error('the host bundle contains no node_modules input: the notice generator is reading the wrong metafile')

const entries = packages.map((pkg) => ({ ...pkg, note: '' }))
for (const excerpt of EXCERPTED) {
  const source = readFileSync(join(here, excerpt.file), 'utf8')
  if (!source.includes(`${excerpt.name}@${excerpt.version}`)) {
    throw new Error(`${excerpt.file} no longer names ${excerpt.name}@${excerpt.version}; update EXCERPTED in build.mjs`)
  }
  const shared = packages.find((pkg) => pkg.name === excerpt.licenseOf)
  if (!shared) throw new Error(`${excerpt.licenseOf} (licence text of ${excerpt.name}) is not bundled`)
  entries.push({
    name: excerpt.name,
    version: excerpt.version,
    license: excerpt.license,
    text: shared.text,
    note: `Verbatim excerpts of this package are in ${excerpt.file}, under the same licence text as ${excerpt.licenseOf} above.`,
  })
}
for (const [folder, version] of [['loader', '1.0.3'], ['include', '1.0.7'], ['group', '1.0.2']]) {
  entries.push({
    name: `@deepseek-ai/cordis-plugin-${folder}`,
    version,
    license: 'MIT',
    text: readLicense(join(here, 'src/dsh/upstream', folder), `vendored ${folder}`),
    note: 'Pinned deepseek-harness 0d1f50007f9bca3f52b06e1c3074fa14d5fb0720. Loader native-internals probe disabled; other runtime semantics reused.',
  })
}
entries.push({name:'@deepseek-ai/dsh-agent-presets',version:'0.1.6-alpha.1',license:'MIT',text:readLicense(join(here,'src/dsh/upstream/agent-presets'),'vendored agent-presets'),note:'Pinned deepseek-harness 0d1f50007f9bca3f52b06e1c3074fa14d5fb0720. Discovery/metadata/specifier/inventory algorithms use mandatory receipt-backed IO; Core owns selection, sessions and writable roots.'})
for (const name of ['dsh-hook-protocol', 'dsh-hooks-claude-code', 'dsh-hooks-codex']) {
  entries.push({
    name: `@deepseek-ai/${name}`,
    version: '0.1.6-alpha.1',
    license: 'MIT',
    text: readLicense(join(here, 'src/dsh/upstream/hooks'), `vendored ${name}`),
    note: 'Pinned deepseek-harness 0d1f50007f9bca3f52b06e1c3074fa14d5fb0720. Pure matcher/codec/merge and configuration parsers reused; local imports and session-writer type declarations adapted. Core retains scheduling and steering.',
  })
}
for (const name of ['dsh-persona', 'dsh-system-prompt']) {
  entries.push({
    name: `@deepseek-ai/${name}`,
    version: '0.1.6-alpha.1',
    license: 'MIT',
    text: readLicense(join(here, 'src/dsh/upstream/hooks'), `adapted ${name}`),
    note: 'Pinned deepseek-harness 0d1f50007f9bca3f52b06e1c3074fa14d5fb0720. Additive persona configuration and strict simple template mapping adapted in src/dsh/persona.ts and the Rust prompt renderer; source and license receipts: src/dsh/persona.UPSTREAM.json. Core retains prompt assembly and accepted model/workspace values.',
  })
}
entries.sort((a, b) => (a.name < b.name ? -1 : 1))

const sections = [
  'Third-party software bundled into codewhale-extension-host.mjs, dsh-composition-review.mjs and builtin/*.mjs.',
  'Generated by crates/tui/extension-host/build.mjs from the bundler metafile; do not edit.',
  '',
  'Packages:',
  ...entries.map((entry) => `  ${entry.name}@${entry.version} (${entry.license})`),
]
for (const entry of entries) {
  sections.push('', '='.repeat(72), `${entry.name}@${entry.version} (${entry.license})`, '='.repeat(72))
  if (entry.note) sections.push('', entry.note)
  sections.push('', entry.text)
}
// Preserve every notice word while keeping generated text free of trailing whitespace.
writeFileSync(join(outdir, 'LICENSES.txt'), sections.join('\n').replace(/[ \t]+$/gm, '') + '\n')
