import { ALL_LOCALES } from "@/lib/i18n/config";

// External contract: contributor print text must cover every language Codewhale
// offers, including the shipped Traditional Chinese TUI/README. This selector
// does not add a website route or change the site's canonical locale registry.
export const MERCH_LANGUAGES = [
  ...ALL_LOCALES.filter((l) => l.status === "shipped" || l.status === "partial"),
  { code: "zh-TW", label: "繁體中文", status: "shipped" as const },
];

const keys = ["title", "lede", "language", "phrase", "identity", "url", "destination", "china", "elsewhere", "size", "costTitle", "production", "processing", "shipping", "total", "note", "quote", "review", "missing", "badIdentity", "badUrl", "draft", "download", "edit", "local", "preview", "source", "costNote", "cta", "product"] as const;
export type MerchCopy = Record<typeof keys[number], string> & { phrases: readonly [string, string, string] };
function copy(values: readonly string[], phrases: MerchCopy["phrases"], product: string): MerchCopy {
  const allValues = [...values, product];
  if (allValues.length !== keys.length) throw new Error("Incomplete contributor copy");
  return { ...Object.fromEntries(keys.map((key, i) => [key, allValues[i]])), phrases } as MerchCopy;
}

/** Draft translations share one key spine. Native-speaker print review is pending. */
export const MERCH_COPY: Record<string, MerchCopy> = {
  en: copy([
    "For the people building Codewhale", "Contributor merch at cost. Add a GitHub username, numeric user ID or a link to your contribution.", "Language / print language", "Print phrase", "GitHub username or user ID", "Contribution link", "Delivery destination", "Mainland China", "Another destination", "Size", "At-cost estimate", "Printed production", "Payment and conversion", "Shipping", "Estimated total", "Final artwork, size, address, tax and exchange rate need confirmation.", "Destination quote required", "Review request", "Add a GitHub identity or contribution link.", "Enter a valid GitHub username or numeric user ID.", "Enter a valid HTTPS contribution link.", "Your local draft", "Download draft", "Edit request", "Local preview. Nothing is sent or charged.", "Print text preview", "Catalog source", "No profit or returns reserve added. Shipping is shown separately.", "View contributor merch",
  ], ["Codewhale contributor", "Built together.", "I helped build Codewhale."], "180gsm cotton T-shirt"),
  zh: copy([
    "献给一起构建 Codewhale 的人", "贡献者周边按成本提供。填写 GitHub 用户名、数字用户 ID 或贡献链接。", "语言 / 印字语言", "印字短语", "GitHub 用户名或用户 ID", "贡献链接", "配送目的地", "中国大陆", "其他目的地", "尺码", "成本价估算", "制作与印刷", "支付与换汇", "运费", "预估合计", "最终图案、尺码、地址、税费及汇率仍需确认。", "需按目的地报价", "查看申请", "请填写 GitHub 身份或贡献链接。", "请输入有效的 GitHub 用户名或数字用户 ID。", "请输入有效的 HTTPS 贡献链接。", "本地草稿", "下载草稿", "修改申请", "本地预览，不会发送信息或收款。", "印字预览", "商品目录来源", "不加利润或退货预留金，运费单独显示。", "查看贡献者周边",
  ], ["Codewhale 贡献者", "一起构建。", "我参与构建了 Codewhale。"], "180 克/平方米纯棉 T 恤"),
  "zh-TW": copy([
    "獻給一起打造 Codewhale 的人", "貢獻者周邊按成本提供。填寫 GitHub 使用者名稱、數字使用者 ID 或貢獻連結。", "語言 / 印字語言", "印字短語", "GitHub 使用者名稱或使用者 ID", "貢獻連結", "配送目的地", "中國大陸", "其他目的地", "尺寸", "成本價估算", "製作與印刷", "支付與換匯", "運費", "預估合計", "最終圖案、尺寸、地址、稅費及匯率仍需確認。", "需按目的地報價", "查看申請", "請填寫 GitHub 身分或貢獻連結。", "請輸入有效的 GitHub 使用者名稱或數字使用者 ID。", "請輸入有效的 HTTPS 貢獻連結。", "本機草稿", "下載草稿", "修改申請", "本機預覽，不會傳送資訊或收款。", "印字預覽", "商品目錄來源", "不加利潤或退貨預留金，運費單獨顯示。", "查看貢獻者周邊",
  ], ["Codewhale 貢獻者", "一起打造。", "我參與打造了 Codewhale。"], "180 克/平方公尺純棉 T 恤"),
  ja: copy([
    "Codewhale を共につくる人へ", "コントリビューター向けグッズを原価で。GitHub ユーザー名、数値 ID、または貢献へのリンクを入力してください。", "言語 / 印字の言語", "印字する言葉", "GitHub ユーザー名または ID", "貢献へのリンク", "配送先", "中国本土", "その他の配送先", "サイズ", "原価の概算", "製作・印刷", "決済・通貨換算", "送料", "合計見積もり", "最終デザイン、サイズ、住所、税金、為替レートは確認が必要です。", "配送先別の見積もりが必要", "リクエストを確認", "GitHub の識別情報か貢献へのリンクを入力してください。", "有効な GitHub ユーザー名または数値 ID を入力してください。", "有効な HTTPS の貢献リンクを入力してください。", "ローカルの下書き", "下書きをダウンロード", "リクエストを編集", "ローカルプレビューです。送信や請求は行いません。", "印字プレビュー", "商品カタログ", "利益や返品準備金を加えません。送料は別に表示します。", "コントリビューター向けグッズを見る",
  ], ["Codewhale コントリビューター", "共につくった。", "Codewhale の開発に参加しました。"], "180g/m² コットンTシャツ"),
  vi: copy([
    "Dành cho những người xây dựng Codewhale", "Hàng dành cho người đóng góp theo giá vốn. Nhập tên GitHub, ID số hoặc liên kết đóng góp.", "Ngôn ngữ / ngôn ngữ in", "Câu in", "Tên hoặc ID người dùng GitHub", "Liên kết đóng góp", "Nơi giao hàng", "Trung Quốc đại lục", "Địa điểm khác", "Kích cỡ", "Ước tính giá vốn", "Sản xuất và in", "Thanh toán và đổi tiền", "Vận chuyển", "Tổng ước tính", "Cần xác nhận mẫu in, kích cỡ, địa chỉ, thuế và tỷ giá cuối cùng.", "Cần báo giá theo nơi giao", "Xem yêu cầu", "Nhập danh tính GitHub hoặc liên kết đóng góp.", "Nhập tên GitHub hoặc ID số hợp lệ.", "Nhập liên kết đóng góp HTTPS hợp lệ.", "Bản nháp cục bộ", "Tải bản nháp", "Sửa yêu cầu", "Xem trước cục bộ. Không gửi dữ liệu hay thu tiền.", "Xem trước chữ in", "Nguồn danh mục", "Không cộng lợi nhuận hay dự phòng trả hàng. Phí vận chuyển hiển thị riêng.", "Xem hàng dành cho người đóng góp",
  ], ["Người đóng góp Codewhale", "Cùng nhau xây dựng.", "Tôi góp phần xây dựng Codewhale."], "Áo thun cotton 180g/m²"),
  ko: copy([
    "Codewhale을 함께 만드는 사람들을 위해", "기여자 상품을 원가로 제공합니다. GitHub 사용자 이름, 숫자 ID 또는 기여 링크를 입력하세요.", "언어 / 인쇄 언어", "인쇄 문구", "GitHub 사용자 이름 또는 ID", "기여 링크", "배송 지역", "중국 본토", "다른 지역", "사이즈", "원가 예상 금액", "제작 및 인쇄", "결제 및 환전", "배송비", "예상 합계", "최종 디자인, 사이즈, 주소, 세금 및 환율을 확인해야 합니다.", "배송 지역별 견적 필요", "요청 확인", "GitHub 정보 또는 기여 링크를 입력하세요.", "올바른 GitHub 사용자 이름 또는 숫자 ID를 입력하세요.", "올바른 HTTPS 기여 링크를 입력하세요.", "로컬 초안", "초안 다운로드", "요청 수정", "로컬 미리보기입니다. 전송이나 결제가 이루어지지 않습니다.", "인쇄 문구 미리보기", "상품 카탈로그 출처", "이익이나 반품 준비금을 추가하지 않습니다. 배송비는 별도로 표시합니다.", "기여자 상품 보기",
  ], ["Codewhale 기여자", "함께 만들었습니다.", "Codewhale 개발에 참여했습니다."], "180g/m² 면 티셔츠"),
  ru: copy([
    "Для тех, кто создаёт Codewhale", "Мерч для участников по себестоимости. Укажите имя GitHub, числовой ID или ссылку на свой вклад.", "Язык / язык надписи", "Надпись", "Имя пользователя или ID GitHub", "Ссылка на вклад", "Место доставки", "Материковый Китай", "Другое место", "Размер", "Расчёт себестоимости", "Изготовление и печать", "Оплата и конвертация", "Доставка", "Предварительный итог", "Нужно подтвердить рисунок, размер, адрес, налоги и курс валют.", "Нужен расчёт для места доставки", "Проверить запрос", "Укажите GitHub или ссылку на свой вклад.", "Введите допустимое имя GitHub или числовой ID.", "Введите допустимую HTTPS-ссылку на вклад.", "Локальный черновик", "Скачать черновик", "Изменить запрос", "Локальный просмотр. Ничего не отправляется и не оплачивается.", "Предпросмотр надписи", "Источник каталога", "Без прибыли и резерва на возвраты. Доставка показана отдельно.", "Мерч для участников",
  ], ["Участник Codewhale", "Создали вместе.", "Я помог создать Codewhale."], "Хлопковая футболка 180 г/м²"),
  uk: copy([
    "Для тих, хто створює Codewhale", "Мерч для учасників за собівартістю. Укажіть ім’я GitHub, числовий ID або посилання на свій внесок.", "Мова / мова напису", "Напис", "Ім’я користувача або ID GitHub", "Посилання на внесок", "Місце доставки", "Материковий Китай", "Інше місце", "Розмір", "Розрахунок собівартості", "Виготовлення та друк", "Оплата й конвертація", "Доставка", "Орієнтовна сума", "Потрібно підтвердити малюнок, розмір, адресу, податки та валютний курс.", "Потрібен розрахунок для місця доставки", "Переглянути запит", "Укажіть GitHub або посилання на свій внесок.", "Введіть дійсне ім’я GitHub або числовий ID.", "Введіть дійсне HTTPS-посилання на внесок.", "Локальна чернетка", "Завантажити чернетку", "Змінити запит", "Локальний перегляд. Нічого не надсилається й не оплачується.", "Попередній вигляд напису", "Джерело каталогу", "Без прибутку та резерву на повернення. Доставка показана окремо.", "Мерч для учасників",
  ], ["Учасник Codewhale", "Створили разом.", "Я допоміг створити Codewhale."], "Бавовняна футболка 180 г/м²"),
  es: copy([
    "Para quienes construyen Codewhale", "Productos para colaboradores a precio de costo. Añade tu nombre de GitHub, ID numérico o enlace a tu contribución.", "Idioma / idioma de impresión", "Frase impresa", "Nombre o ID de GitHub", "Enlace a la contribución", "Destino de entrega", "China continental", "Otro destino", "Talla", "Estimación al costo", "Producción e impresión", "Pago y conversión", "Envío", "Total estimado", "Falta confirmar el diseño, la talla, la dirección, los impuestos y el cambio.", "Se necesita cotización para el destino", "Revisar solicitud", "Añade tu identidad de GitHub o un enlace a tu contribución.", "Introduce un nombre de GitHub o ID numérico válido.", "Introduce un enlace HTTPS válido a tu contribución.", "Tu borrador local", "Descargar borrador", "Editar solicitud", "Vista previa local. No se envía nada ni se cobra.", "Vista previa del texto", "Catálogo de origen", "Sin ganancias ni reserva para devoluciones. El envío se muestra por separado.", "Ver productos para colaboradores",
  ], ["Colaborador de Codewhale", "Construido en equipo.", "Ayudé a crear Codewhale."], "Camiseta de algodón de 180 g/m²"),
  "pt-BR": copy([
    "Para quem constrói o Codewhale", "Produtos para colaboradores a preço de custo. Informe seu nome no GitHub, ID numérico ou link da contribuição.", "Idioma / idioma da impressão", "Frase impressa", "Nome ou ID do GitHub", "Link da contribuição", "Destino da entrega", "China continental", "Outro destino", "Tamanho", "Estimativa de custo", "Produção e impressão", "Pagamento e conversão", "Frete", "Total estimado", "A arte, o tamanho, o endereço, os impostos e o câmbio final precisam ser confirmados.", "É preciso cotar o destino", "Revisar solicitação", "Informe uma identidade do GitHub ou um link da contribuição.", "Informe um nome do GitHub ou ID numérico válido.", "Informe um link HTTPS válido da contribuição.", "Seu rascunho local", "Baixar rascunho", "Editar solicitação", "Prévia local. Nada é enviado ou cobrado.", "Prévia do texto", "Catálogo de origem", "Sem lucro ou reserva para devoluções. O frete aparece separadamente.", "Ver produtos para colaboradores",
  ], ["Colaborador do Codewhale", "Construído em conjunto.", "Ajudei a criar o Codewhale."], "Camiseta de algodão de 180 g/m²"),
  fr: copy([
    "Pour celles et ceux qui construisent Codewhale", "Des articles pour les contributeurs à prix coûtant. Indiquez votre nom GitHub, votre identifiant numérique ou un lien vers votre contribution.", "Langue / langue d’impression", "Phrase imprimée", "Nom ou identifiant GitHub", "Lien vers la contribution", "Destination de livraison", "Chine continentale", "Autre destination", "Taille", "Estimation au prix coûtant", "Fabrication et impression", "Paiement et conversion", "Livraison", "Total estimé", "Le visuel, la taille, l’adresse, les taxes et le taux de change restent à confirmer.", "Devis requis pour la destination", "Vérifier la demande", "Ajoutez une identité GitHub ou un lien vers votre contribution.", "Saisissez un nom GitHub ou un identifiant numérique valide.", "Saisissez un lien HTTPS valide vers votre contribution.", "Votre brouillon local", "Télécharger le brouillon", "Modifier la demande", "Aperçu local. Rien n’est envoyé ni facturé.", "Aperçu du texte", "Catalogue d’origine", "Sans bénéfice ni provision pour retours. Livraison affichée séparément.", "Voir les articles pour contributeurs",
  ], ["Contributeur Codewhale", "Construit ensemble.", "J’ai contribué à créer Codewhale."], "T-shirt en coton de 180 g/m²"),
  de: copy([
    "Für alle, die Codewhale mitgestalten", "Merch für Mitwirkende zum Selbstkostenpreis. Gib deinen GitHub-Namen, deine numerische ID oder einen Beitragslink an.", "Sprache / Drucksprache", "Drucktext", "GitHub-Name oder Benutzer-ID", "Link zum Beitrag", "Lieferziel", "Festlandchina", "Anderes Lieferziel", "Größe", "Selbstkostenschätzung", "Herstellung und Druck", "Zahlung und Umrechnung", "Versand", "Geschätzte Gesamtsumme", "Motiv, Größe, Adresse, Steuern und Wechselkurs müssen bestätigt werden.", "Angebot für das Lieferziel erforderlich", "Anfrage prüfen", "Gib eine GitHub-Identität oder einen Beitragslink an.", "Gib einen gültigen GitHub-Namen oder eine numerische ID an.", "Gib einen gültigen HTTPS-Beitragslink an.", "Dein lokaler Entwurf", "Entwurf herunterladen", "Anfrage bearbeiten", "Lokale Vorschau. Nichts wird versendet oder berechnet.", "Drucktextvorschau", "Produktkatalog", "Ohne Gewinn oder Rücklagen für Retouren. Versand wird separat ausgewiesen.", "Merch für Mitwirkende ansehen",
  ], ["Codewhale-Mitwirkende", "Gemeinsam gebaut.", "Ich habe Codewhale mitentwickelt."], "Baumwoll-T-Shirt mit 180 g/m²"),
  ca: copy([
    "Per a qui construeix Codewhale", "Articles per a col·laboradors a preu de cost. Afegeix el nom de GitHub, l’ID numèric o un enllaç a la contribució.", "Idioma / idioma d’impressió", "Frase impresa", "Nom o ID de GitHub", "Enllaç a la contribució", "Destinació de lliurament", "Xina continental", "Una altra destinació", "Talla", "Estimació a preu de cost", "Fabricació i impressió", "Pagament i conversió", "Enviament", "Total estimat", "Cal confirmar el disseny, la talla, l’adreça, els impostos i el canvi.", "Cal un pressupost per a la destinació", "Revisar la sol·licitud", "Afegeix una identitat de GitHub o un enllaç a la contribució.", "Introdueix un nom de GitHub o un ID numèric vàlid.", "Introdueix un enllaç HTTPS vàlid a la contribució.", "El teu esborrany local", "Descarregar l’esborrany", "Editar la sol·licitud", "Vista prèvia local. No s’envia ni es cobra res.", "Vista prèvia del text", "Catàleg d’origen", "Sense benefici ni reserva per a devolucions. L’enviament es mostra per separat.", "Veure articles per a col·laboradors",
  ], ["Col·laborador de Codewhale", "Construït plegats.", "He ajudat a crear Codewhale."], "Samarreta de cotó de 180 g/m²"),
  id: copy([
    "Untuk mereka yang membangun Codewhale", "Merch kontributor dengan harga pokok. Masukkan nama GitHub, ID numerik, atau tautan kontribusi.", "Bahasa / bahasa cetak", "Frasa cetak", "Nama pengguna atau ID GitHub", "Tautan kontribusi", "Tujuan pengiriman", "Tiongkok daratan", "Tujuan lain", "Ukuran", "Perkiraan harga pokok", "Produksi dan cetak", "Pembayaran dan konversi", "Pengiriman", "Perkiraan total", "Desain akhir, ukuran, alamat, pajak, dan kurs perlu dikonfirmasi.", "Perlu penawaran sesuai tujuan", "Tinjau permintaan", "Tambahkan identitas GitHub atau tautan kontribusi.", "Masukkan nama GitHub atau ID numerik yang valid.", "Masukkan tautan kontribusi HTTPS yang valid.", "Draf lokal Anda", "Unduh draf", "Ubah permintaan", "Pratinjau lokal. Tidak ada data dikirim atau biaya dikenakan.", "Pratinjau teks cetak", "Sumber katalog", "Tanpa laba atau cadangan pengembalian. Ongkir ditampilkan terpisah.", "Lihat merch kontributor",
  ], ["Kontributor Codewhale", "Dibangun bersama.", "Saya ikut membangun Codewhale."], "Kaus katun 180g/m²"),
  hi: copy([
    "Codewhale बनाने वाले लोगों के लिए", "योगदानकर्ताओं के लिए लागत पर मर्च। GitHub उपयोगकर्ता नाम, संख्यात्मक ID या योगदान का लिंक दें।", "भाषा / प्रिंट की भाषा", "प्रिंट का वाक्य", "GitHub उपयोगकर्ता नाम या ID", "योगदान का लिंक", "डिलीवरी स्थान", "मुख्यभूमि चीन", "अन्य स्थान", "आकार", "लागत का अनुमान", "निर्माण और प्रिंट", "भुगतान और मुद्रा परिवर्तन", "डिलीवरी", "अनुमानित कुल", "अंतिम डिज़ाइन, आकार, पता, कर और विनिमय दर की पुष्टि बाकी है।", "स्थान के अनुसार मूल्य चाहिए", "अनुरोध देखें", "GitHub पहचान या योगदान का लिंक दें।", "मान्य GitHub नाम या संख्यात्मक ID दें।", "योगदान का मान्य HTTPS लिंक दें।", "आपका स्थानीय मसौदा", "मसौदा डाउनलोड करें", "अनुरोध बदलें", "स्थानीय पूर्वावलोकन। कुछ भेजा या शुल्क नहीं लिया जाता।", "प्रिंट पाठ का पूर्वावलोकन", "कैटलॉग स्रोत", "लाभ या वापसी आरक्षित राशि नहीं जोड़ी गई है। डिलीवरी अलग दिखाई गई है।", "योगदानकर्ता मर्च देखें",
  ], ["Codewhale योगदानकर्ता", "मिलकर बनाया।", "मैंने Codewhale बनाने में मदद की।"], "180 ग्राम/वर्ग मीटर कॉटन टी-शर्ट"),
  tr: copy([
    "Codewhale’i geliştirenler için", "Katkıcılara maliyetine ürünler. GitHub adınızı, sayısal kullanıcı ID’nizi veya katkı bağlantısını ekleyin.", "Dil / baskı dili", "Baskı ifadesi", "GitHub adı veya kullanıcı ID’si", "Katkı bağlantısı", "Teslimat yeri", "Çin anakarası", "Başka bir yer", "Beden", "Maliyet tahmini", "Üretim ve baskı", "Ödeme ve dönüşüm", "Kargo", "Tahmini toplam", "Son tasarım, beden, adres, vergi ve döviz kuru doğrulanmalıdır.", "Teslimat yerine göre teklif gerekli", "Talebi incele", "GitHub kimliği veya katkı bağlantısı ekleyin.", "Geçerli bir GitHub adı veya sayısal ID girin.", "Geçerli bir HTTPS katkı bağlantısı girin.", "Yerel taslağınız", "Taslağı indir", "Talebi düzenle", "Yerel önizleme. Hiçbir şey gönderilmez veya ücretlendirilmez.", "Baskı metni önizlemesi", "Katalog kaynağı", "Kâr veya iade rezervi eklenmez. Kargo ayrı gösterilir.", "Katkıcı ürünlerini gör",
  ], ["Codewhale katkıcısı", "Birlikte inşa ettik.", "Codewhale’i oluşturmaya yardımcı oldum."], "180 g/m² pamuklu tişört"),
  it: copy([
    "Per chi costruisce Codewhale", "Articoli per i contributori a prezzo di costo. Inserisci il nome GitHub, l’ID numerico o un link al contributo.", "Lingua / lingua di stampa", "Frase stampata", "Nome o ID GitHub", "Link al contributo", "Destinazione di consegna", "Cina continentale", "Altra destinazione", "Taglia", "Stima del prezzo di costo", "Produzione e stampa", "Pagamento e conversione", "Spedizione", "Totale stimato", "Grafica, taglia, indirizzo, imposte e cambio finale devono essere confermati.", "Serve un preventivo per la destinazione", "Rivedi la richiesta", "Aggiungi un’identità GitHub o un link al contributo.", "Inserisci un nome GitHub o un ID numerico valido.", "Inserisci un link HTTPS valido al contributo.", "La tua bozza locale", "Scarica la bozza", "Modifica la richiesta", "Anteprima locale. Nulla viene inviato o addebitato.", "Anteprima del testo", "Catalogo di origine", "Senza profitto né riserva per i resi. La spedizione è mostrata a parte.", "Vedi gli articoli per contributori",
  ], ["Contributore Codewhale", "Costruito insieme.", "Ho aiutato a creare Codewhale."], "T-shirt in cotone da 180 g/m²"),
  pl: copy([
    "Dla osób tworzących Codewhale", "Produkty dla współtwórców po kosztach. Podaj nazwę GitHub, numeryczne ID lub link do wkładu.", "Język / język nadruku", "Tekst nadruku", "Nazwa użytkownika lub ID GitHub", "Link do wkładu", "Miejsce dostawy", "Chiny kontynentalne", "Inne miejsce", "Rozmiar", "Szacunkowy koszt", "Produkcja i nadruk", "Płatność i przewalutowanie", "Wysyłka", "Szacunkowa suma", "Trzeba potwierdzić grafikę, rozmiar, adres, podatki i kurs walut.", "Potrzebna wycena dla miejsca dostawy", "Sprawdź zgłoszenie", "Podaj dane GitHub lub link do wkładu.", "Podaj prawidłową nazwę GitHub lub numeryczne ID.", "Podaj prawidłowy link HTTPS do wkładu.", "Twój lokalny szkic", "Pobierz szkic", "Edytuj zgłoszenie", "Podgląd lokalny. Nic nie jest wysyłane ani pobierane.", "Podgląd tekstu nadruku", "Źródło katalogu", "Bez zysku i rezerwy na zwroty. Wysyłka jest pokazana osobno.", "Zobacz produkty dla współtwórców",
  ], ["Współtwórca Codewhale", "Zbudowane razem.", "Pomogłem stworzyć Codewhale."], "Bawełniany T-shirt 180 g/m²"),
  ar: copy([
    "لمن يساهمون في بناء Codewhale", "منتجات للمساهمين بسعر التكلفة. أضف اسم GitHub أو المعرّف الرقمي أو رابط مساهمتك.", "اللغة / لغة الطباعة", "العبارة المطبوعة", "اسم مستخدم GitHub أو معرّفه", "رابط المساهمة", "وجهة التوصيل", "الصين القارية", "وجهة أخرى", "المقاس", "تقدير سعر التكلفة", "الإنتاج والطباعة", "الدفع وتحويل العملة", "الشحن", "الإجمالي التقديري", "يجب تأكيد التصميم والمقاس والعنوان والضرائب وسعر الصرف النهائي.", "يلزم عرض سعر للوجهة", "مراجعة الطلب", "أضف هوية GitHub أو رابط مساهمتك.", "أدخل اسم GitHub أو معرّفًا رقميًا صالحًا.", "أدخل رابط مساهمة HTTPS صالحًا.", "مسودتك المحلية", "تنزيل المسودة", "تعديل الطلب", "معاينة محلية. لا يتم إرسال شيء أو تحصيل أي مبلغ.", "معاينة النص المطبوع", "مصدر الكتالوج", "لا تُضاف أرباح أو مخصصات للمرتجعات. يُعرض الشحن منفصلًا.", "عرض منتجات المساهمين",
  ], ["مساهم في Codewhale", "بنيناها معًا.", "ساعدت في بناء Codewhale."], "قميص قطني قصير الأكمام بوزن 180 غ/م²"),
};

export function getMerchCopy(locale: string): MerchCopy {
  return MERCH_COPY[locale === "zh-Hant" ? "zh-TW" : locale] ?? MERCH_COPY.en;
}
